// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"inventory/ent/entgen/tblauthclient"
	"inventory/ent/entgen/tblauthtoken"
	"inventory/ent/entgen/tblcart"
	"inventory/ent/entgen/tblinventory"
	"inventory/ent/entgen/tblinventorytag"
	"inventory/ent/entgen/tblpayment"
	"inventory/ent/entgen/tbltag"
	"inventory/ent/entgen/tbluser"
	"inventory/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tblauthclientFields := schema.TblAuthClient{}.Fields()
	_ = tblauthclientFields
	// tblauthclientDescCreatedAt is the schema descriptor for CreatedAt field.
	tblauthclientDescCreatedAt := tblauthclientFields[3].Descriptor()
	// tblauthclient.DefaultCreatedAt holds the default value on creation for the CreatedAt field.
	tblauthclient.DefaultCreatedAt = tblauthclientDescCreatedAt.Default.(time.Time)
	// tblauthclientDescUpdatedAt is the schema descriptor for UpdatedAt field.
	tblauthclientDescUpdatedAt := tblauthclientFields[4].Descriptor()
	// tblauthclient.DefaultUpdatedAt holds the default value on creation for the UpdatedAt field.
	tblauthclient.DefaultUpdatedAt = tblauthclientDescUpdatedAt.Default.(time.Time)
	// tblauthclientDescPublic is the schema descriptor for public field.
	tblauthclientDescPublic := tblauthclientFields[7].Descriptor()
	// tblauthclient.DefaultPublic holds the default value on creation for the public field.
	tblauthclient.DefaultPublic = tblauthclientDescPublic.Default.(bool)
	// tblauthclientDescUserAgent is the schema descriptor for UserAgent field.
	tblauthclientDescUserAgent := tblauthclientFields[8].Descriptor()
	// tblauthclient.DefaultUserAgent holds the default value on creation for the UserAgent field.
	tblauthclient.DefaultUserAgent = tblauthclientDescUserAgent.Default.(string)
	// tblauthclientDescCreatedBy is the schema descriptor for CreatedBy field.
	tblauthclientDescCreatedBy := tblauthclientFields[10].Descriptor()
	// tblauthclient.DefaultCreatedBy holds the default value on creation for the CreatedBy field.
	tblauthclient.DefaultCreatedBy = tblauthclientDescCreatedBy.Default.(string)
	// tblauthclientDescUpdatedBy is the schema descriptor for UpdatedBy field.
	tblauthclientDescUpdatedBy := tblauthclientFields[11].Descriptor()
	// tblauthclient.DefaultUpdatedBy holds the default value on creation for the UpdatedBy field.
	tblauthclient.DefaultUpdatedBy = tblauthclientDescUpdatedBy.Default.(string)
	tblauthtokenFields := schema.TblAuthToken{}.Fields()
	_ = tblauthtokenFields
	// tblauthtokenDescAccesstokencreatedat is the schema descriptor for accesstokencreatedat field.
	tblauthtokenDescAccesstokencreatedat := tblauthtokenFields[4].Descriptor()
	// tblauthtoken.DefaultAccesstokencreatedat holds the default value on creation for the accesstokencreatedat field.
	tblauthtoken.DefaultAccesstokencreatedat = tblauthtokenDescAccesstokencreatedat.Default.(time.Time)
	// tblauthtokenDescRefreshtokencreatedat is the schema descriptor for refreshtokencreatedat field.
	tblauthtokenDescRefreshtokencreatedat := tblauthtokenFields[9].Descriptor()
	// tblauthtoken.DefaultRefreshtokencreatedat holds the default value on creation for the refreshtokencreatedat field.
	tblauthtoken.DefaultRefreshtokencreatedat = tblauthtokenDescRefreshtokencreatedat.Default.(time.Time)
	// tblauthtokenDescCreatedat is the schema descriptor for createdat field.
	tblauthtokenDescCreatedat := tblauthtokenFields[11].Descriptor()
	// tblauthtoken.DefaultCreatedat holds the default value on creation for the createdat field.
	tblauthtoken.DefaultCreatedat = tblauthtokenDescCreatedat.Default.(time.Time)
	// tblauthtokenDescUpdatedat is the schema descriptor for updatedat field.
	tblauthtokenDescUpdatedat := tblauthtokenFields[12].Descriptor()
	// tblauthtoken.DefaultUpdatedat holds the default value on creation for the updatedat field.
	tblauthtoken.DefaultUpdatedat = tblauthtokenDescUpdatedat.Default.(time.Time)
	// tblauthtokenDescIPAddress is the schema descriptor for ip_address field.
	tblauthtokenDescIPAddress := tblauthtokenFields[14].Descriptor()
	// tblauthtoken.DefaultIPAddress holds the default value on creation for the ip_address field.
	tblauthtoken.DefaultIPAddress = tblauthtokenDescIPAddress.Default.(string)
	// tblauthtokenDescUseragent is the schema descriptor for useragent field.
	tblauthtokenDescUseragent := tblauthtokenFields[15].Descriptor()
	// tblauthtoken.DefaultUseragent holds the default value on creation for the useragent field.
	tblauthtoken.DefaultUseragent = tblauthtokenDescUseragent.Default.(string)
	// tblauthtokenDescCreatedby is the schema descriptor for createdby field.
	tblauthtokenDescCreatedby := tblauthtokenFields[16].Descriptor()
	// tblauthtoken.DefaultCreatedby holds the default value on creation for the createdby field.
	tblauthtoken.DefaultCreatedby = tblauthtokenDescCreatedby.Default.(string)
	// tblauthtokenDescUpdatedby is the schema descriptor for updatedby field.
	tblauthtokenDescUpdatedby := tblauthtokenFields[17].Descriptor()
	// tblauthtoken.DefaultUpdatedby holds the default value on creation for the updatedby field.
	tblauthtoken.DefaultUpdatedby = tblauthtokenDescUpdatedby.Default.(string)
	// tblauthtokenDescCodecreatedat is the schema descriptor for codecreatedat field.
	tblauthtokenDescCodecreatedat := tblauthtokenFields[20].Descriptor()
	// tblauthtoken.DefaultCodecreatedat holds the default value on creation for the codecreatedat field.
	tblauthtoken.DefaultCodecreatedat = tblauthtokenDescCodecreatedat.Default.(time.Time)
	// tblauthtokenDescScope is the schema descriptor for scope field.
	tblauthtokenDescScope := tblauthtokenFields[24].Descriptor()
	// tblauthtoken.DefaultScope holds the default value on creation for the scope field.
	tblauthtoken.DefaultScope = tblauthtokenDescScope.Default.(string)
	tblcartFields := schema.TblCart{}.Fields()
	_ = tblcartFields
	// tblcartDescCreatedAt is the schema descriptor for Created_at field.
	tblcartDescCreatedAt := tblcartFields[4].Descriptor()
	// tblcart.DefaultCreatedAt holds the default value on creation for the Created_at field.
	tblcart.DefaultCreatedAt = tblcartDescCreatedAt.Default.(func() time.Time)
	tblinventoryFields := schema.TblInventory{}.Fields()
	_ = tblinventoryFields
	// tblinventoryDescName is the schema descriptor for Name field.
	tblinventoryDescName := tblinventoryFields[1].Descriptor()
	// tblinventory.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	tblinventory.NameValidator = tblinventoryDescName.Validators[0].(func(string) error)
	// tblinventoryDescDescription is the schema descriptor for Description field.
	tblinventoryDescDescription := tblinventoryFields[2].Descriptor()
	// tblinventory.DescriptionValidator is a validator for the "Description" field. It is called by the builders before save.
	tblinventory.DescriptionValidator = tblinventoryDescDescription.Validators[0].(func(string) error)
	// tblinventoryDescIsActive is the schema descriptor for Is_Active field.
	tblinventoryDescIsActive := tblinventoryFields[5].Descriptor()
	// tblinventory.DefaultIsActive holds the default value on creation for the Is_Active field.
	tblinventory.DefaultIsActive = tblinventoryDescIsActive.Default.(bool)
	// tblinventoryDescCreatedAt is the schema descriptor for Created_at field.
	tblinventoryDescCreatedAt := tblinventoryFields[6].Descriptor()
	// tblinventory.DefaultCreatedAt holds the default value on creation for the Created_at field.
	tblinventory.DefaultCreatedAt = tblinventoryDescCreatedAt.Default.(func() time.Time)
	tblinventorytagFields := schema.TblInventoryTag{}.Fields()
	_ = tblinventorytagFields
	// tblinventorytagDescCreatedAt is the schema descriptor for Created_at field.
	tblinventorytagDescCreatedAt := tblinventorytagFields[3].Descriptor()
	// tblinventorytag.DefaultCreatedAt holds the default value on creation for the Created_at field.
	tblinventorytag.DefaultCreatedAt = tblinventorytagDescCreatedAt.Default.(func() time.Time)
	tblpaymentFields := schema.TblPayment{}.Fields()
	_ = tblpaymentFields
	// tblpaymentDescStatus is the schema descriptor for Status field.
	tblpaymentDescStatus := tblpaymentFields[3].Descriptor()
	// tblpayment.DefaultStatus holds the default value on creation for the Status field.
	tblpayment.DefaultStatus = tblpaymentDescStatus.Default.(string)
	// tblpaymentDescRazorpayOrderId is the schema descriptor for RazorpayOrderId field.
	tblpaymentDescRazorpayOrderId := tblpaymentFields[4].Descriptor()
	// tblpayment.RazorpayOrderIdValidator is a validator for the "RazorpayOrderId" field. It is called by the builders before save.
	tblpayment.RazorpayOrderIdValidator = tblpaymentDescRazorpayOrderId.Validators[0].(func(string) error)
	// tblpaymentDescCreatedAt is the schema descriptor for Created_at field.
	tblpaymentDescCreatedAt := tblpaymentFields[6].Descriptor()
	// tblpayment.DefaultCreatedAt holds the default value on creation for the Created_at field.
	tblpayment.DefaultCreatedAt = tblpaymentDescCreatedAt.Default.(func() time.Time)
	tbltagFields := schema.TblTag{}.Fields()
	_ = tbltagFields
	// tbltagDescName is the schema descriptor for Name field.
	tbltagDescName := tbltagFields[1].Descriptor()
	// tbltag.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	tbltag.NameValidator = tbltagDescName.Validators[0].(func(string) error)
	// tbltagDescDescription is the schema descriptor for Description field.
	tbltagDescDescription := tbltagFields[2].Descriptor()
	// tbltag.DescriptionValidator is a validator for the "Description" field. It is called by the builders before save.
	tbltag.DescriptionValidator = tbltagDescDescription.Validators[0].(func(string) error)
	// tbltagDescIsActive is the schema descriptor for Is_Active field.
	tbltagDescIsActive := tbltagFields[3].Descriptor()
	// tbltag.DefaultIsActive holds the default value on creation for the Is_Active field.
	tbltag.DefaultIsActive = tbltagDescIsActive.Default.(bool)
	// tbltagDescCreatedAt is the schema descriptor for Created_at field.
	tbltagDescCreatedAt := tbltagFields[4].Descriptor()
	// tbltag.DefaultCreatedAt holds the default value on creation for the Created_at field.
	tbltag.DefaultCreatedAt = tbltagDescCreatedAt.Default.(func() time.Time)
	tbluserFields := schema.TblUser{}.Fields()
	_ = tbluserFields
	// tbluserDescFirstname is the schema descriptor for firstname field.
	tbluserDescFirstname := tbluserFields[1].Descriptor()
	// tbluser.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	tbluser.FirstnameValidator = func() func(string) error {
		validators := tbluserDescFirstname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(firstname string) error {
			for _, fn := range fns {
				if err := fn(firstname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tbluserDescLastname is the schema descriptor for lastname field.
	tbluserDescLastname := tbluserFields[2].Descriptor()
	// tbluser.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	tbluser.LastnameValidator = func() func(string) error {
		validators := tbluserDescLastname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(lastname string) error {
			for _, fn := range fns {
				if err := fn(lastname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tbluserDescEmail is the schema descriptor for email field.
	tbluserDescEmail := tbluserFields[3].Descriptor()
	// tbluser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	tbluser.EmailValidator = func() func(string) error {
		validators := tbluserDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tbluserDescPassword is the schema descriptor for password field.
	tbluserDescPassword := tbluserFields[5].Descriptor()
	// tbluser.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	tbluser.PasswordValidator = func() func(string) error {
		validators := tbluserDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tbluserDescIsActive is the schema descriptor for is_active field.
	tbluserDescIsActive := tbluserFields[6].Descriptor()
	// tbluser.DefaultIsActive holds the default value on creation for the is_active field.
	tbluser.DefaultIsActive = tbluserDescIsActive.Default.(int)
	// tbluserDescIPAddress is the schema descriptor for ip_address field.
	tbluserDescIPAddress := tbluserFields[9].Descriptor()
	// tbluser.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	tbluser.IPAddressValidator = tbluserDescIPAddress.Validators[0].(func(string) error)
	// tbluserDescCreatedAt is the schema descriptor for created_at field.
	tbluserDescCreatedAt := tbluserFields[10].Descriptor()
	// tbluser.DefaultCreatedAt holds the default value on creation for the created_at field.
	tbluser.DefaultCreatedAt = tbluserDescCreatedAt.Default.(func() time.Time)
	// tbluserDescUpdatedAt is the schema descriptor for updated_at field.
	tbluserDescUpdatedAt := tbluserFields[11].Descriptor()
	// tbluser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tbluser.DefaultUpdatedAt = tbluserDescUpdatedAt.Default.(func() time.Time)
	// tbluser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tbluser.UpdateDefaultUpdatedAt = tbluserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tbluserDescID is the schema descriptor for id field.
	tbluserDescID := tbluserFields[0].Descriptor()
	// tbluser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tbluser.IDValidator = tbluserDescID.Validators[0].(func(string) error)
}
