// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"inventory/ent/entgen/predicate"
	"inventory/ent/entgen/tblcart"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TblCartDelete is the builder for deleting a TblCart entity.
type TblCartDelete struct {
	config
	hooks    []Hook
	mutation *TblCartMutation
}

// Where appends a list predicates to the TblCartDelete builder.
func (tcd *TblCartDelete) Where(ps ...predicate.TblCart) *TblCartDelete {
	tcd.mutation.Where(ps...)
	return tcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tcd *TblCartDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tcd.sqlExec, tcd.mutation, tcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tcd *TblCartDelete) ExecX(ctx context.Context) int {
	n, err := tcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tcd *TblCartDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tblcart.Table, sqlgraph.NewFieldSpec(tblcart.FieldID, field.TypeString))
	if ps := tcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tcd.mutation.done = true
	return affected, err
}

// TblCartDeleteOne is the builder for deleting a single TblCart entity.
type TblCartDeleteOne struct {
	tcd *TblCartDelete
}

// Where appends a list predicates to the TblCartDelete builder.
func (tcdo *TblCartDeleteOne) Where(ps ...predicate.TblCart) *TblCartDeleteOne {
	tcdo.tcd.mutation.Where(ps...)
	return tcdo
}

// Exec executes the deletion query.
func (tcdo *TblCartDeleteOne) Exec(ctx context.Context) error {
	n, err := tcdo.tcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tblcart.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tcdo *TblCartDeleteOne) ExecX(ctx context.Context) {
	if err := tcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
