// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"fmt"
	"inventory/ent/entgen/predicate"
	"inventory/ent/entgen/tblinventory"
	"inventory/ent/entgen/tblpayment"
	"inventory/ent/entgen/tbluser"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TblPaymentQuery is the builder for querying TblPayment entities.
type TblPaymentQuery struct {
	config
	ctx           *QueryContext
	order         []tblpayment.OrderOption
	inters        []Interceptor
	predicates    []predicate.TblPayment
	withInventory *TblInventoryQuery
	withUser      *TblUserQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TblPaymentQuery builder.
func (tpq *TblPaymentQuery) Where(ps ...predicate.TblPayment) *TblPaymentQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit the number of records to be returned by this query.
func (tpq *TblPaymentQuery) Limit(limit int) *TblPaymentQuery {
	tpq.ctx.Limit = &limit
	return tpq
}

// Offset to start from.
func (tpq *TblPaymentQuery) Offset(offset int) *TblPaymentQuery {
	tpq.ctx.Offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TblPaymentQuery) Unique(unique bool) *TblPaymentQuery {
	tpq.ctx.Unique = &unique
	return tpq
}

// Order specifies how the records should be ordered.
func (tpq *TblPaymentQuery) Order(o ...tblpayment.OrderOption) *TblPaymentQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// QueryInventory chains the current query on the "Inventory" edge.
func (tpq *TblPaymentQuery) QueryInventory() *TblInventoryQuery {
	query := (&TblInventoryClient{config: tpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tblpayment.Table, tblpayment.FieldID, selector),
			sqlgraph.To(tblinventory.Table, tblinventory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tblpayment.InventoryTable, tblpayment.InventoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "User" edge.
func (tpq *TblPaymentQuery) QueryUser() *TblUserQuery {
	query := (&TblUserClient{config: tpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tblpayment.Table, tblpayment.FieldID, selector),
			sqlgraph.To(tbluser.Table, tbluser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tblpayment.UserTable, tblpayment.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TblPayment entity from the query.
// Returns a *NotFoundError when no TblPayment was found.
func (tpq *TblPaymentQuery) First(ctx context.Context) (*TblPayment, error) {
	nodes, err := tpq.Limit(1).All(setContextOp(ctx, tpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tblpayment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TblPaymentQuery) FirstX(ctx context.Context) *TblPayment {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TblPayment ID from the query.
// Returns a *NotFoundError when no TblPayment ID was found.
func (tpq *TblPaymentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tpq.Limit(1).IDs(setContextOp(ctx, tpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tblpayment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TblPaymentQuery) FirstIDX(ctx context.Context) string {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TblPayment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TblPayment entity is found.
// Returns a *NotFoundError when no TblPayment entities are found.
func (tpq *TblPaymentQuery) Only(ctx context.Context) (*TblPayment, error) {
	nodes, err := tpq.Limit(2).All(setContextOp(ctx, tpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tblpayment.Label}
	default:
		return nil, &NotSingularError{tblpayment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TblPaymentQuery) OnlyX(ctx context.Context) *TblPayment {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TblPayment ID in the query.
// Returns a *NotSingularError when more than one TblPayment ID is found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TblPaymentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = tpq.Limit(2).IDs(setContextOp(ctx, tpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tblpayment.Label}
	default:
		err = &NotSingularError{tblpayment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TblPaymentQuery) OnlyIDX(ctx context.Context) string {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TblPayments.
func (tpq *TblPaymentQuery) All(ctx context.Context) ([]*TblPayment, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryAll)
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TblPayment, *TblPaymentQuery]()
	return withInterceptors[[]*TblPayment](ctx, tpq, qr, tpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TblPaymentQuery) AllX(ctx context.Context) []*TblPayment {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TblPayment IDs.
func (tpq *TblPaymentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if tpq.ctx.Unique == nil && tpq.path != nil {
		tpq.Unique(true)
	}
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryIDs)
	if err = tpq.Select(tblpayment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TblPaymentQuery) IDsX(ctx context.Context) []string {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TblPaymentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryCount)
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tpq, querierCount[*TblPaymentQuery](), tpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TblPaymentQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TblPaymentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tpq.ctx, ent.OpQueryExist)
	switch _, err := tpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TblPaymentQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TblPaymentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TblPaymentQuery) Clone() *TblPaymentQuery {
	if tpq == nil {
		return nil
	}
	return &TblPaymentQuery{
		config:        tpq.config,
		ctx:           tpq.ctx.Clone(),
		order:         append([]tblpayment.OrderOption{}, tpq.order...),
		inters:        append([]Interceptor{}, tpq.inters...),
		predicates:    append([]predicate.TblPayment{}, tpq.predicates...),
		withInventory: tpq.withInventory.Clone(),
		withUser:      tpq.withUser.Clone(),
		// clone intermediate query.
		sql:  tpq.sql.Clone(),
		path: tpq.path,
	}
}

// WithInventory tells the query-builder to eager-load the nodes that are connected to
// the "Inventory" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TblPaymentQuery) WithInventory(opts ...func(*TblInventoryQuery)) *TblPaymentQuery {
	query := (&TblInventoryClient{config: tpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tpq.withInventory = query
	return tpq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "User" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TblPaymentQuery) WithUser(opts ...func(*TblUserQuery)) *TblPaymentQuery {
	query := (&TblUserClient{config: tpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tpq.withUser = query
	return tpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InventoryId string `json:"InventoryId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TblPayment.Query().
//		GroupBy(tblpayment.FieldInventoryId).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (tpq *TblPaymentQuery) GroupBy(field string, fields ...string) *TblPaymentGroupBy {
	tpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TblPaymentGroupBy{build: tpq}
	grbuild.flds = &tpq.ctx.Fields
	grbuild.label = tblpayment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InventoryId string `json:"InventoryId,omitempty"`
//	}
//
//	client.TblPayment.Query().
//		Select(tblpayment.FieldInventoryId).
//		Scan(ctx, &v)
func (tpq *TblPaymentQuery) Select(fields ...string) *TblPaymentSelect {
	tpq.ctx.Fields = append(tpq.ctx.Fields, fields...)
	sbuild := &TblPaymentSelect{TblPaymentQuery: tpq}
	sbuild.label = tblpayment.Label
	sbuild.flds, sbuild.scan = &tpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TblPaymentSelect configured with the given aggregations.
func (tpq *TblPaymentQuery) Aggregate(fns ...AggregateFunc) *TblPaymentSelect {
	return tpq.Select().Aggregate(fns...)
}

func (tpq *TblPaymentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tpq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tpq); err != nil {
				return err
			}
		}
	}
	for _, f := range tpq.ctx.Fields {
		if !tblpayment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TblPaymentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TblPayment, error) {
	var (
		nodes       = []*TblPayment{}
		_spec       = tpq.querySpec()
		loadedTypes = [2]bool{
			tpq.withInventory != nil,
			tpq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TblPayment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TblPayment{config: tpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tpq.modifiers) > 0 {
		_spec.Modifiers = tpq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tpq.withInventory; query != nil {
		if err := tpq.loadInventory(ctx, query, nodes, nil,
			func(n *TblPayment, e *TblInventory) { n.Edges.Inventory = e }); err != nil {
			return nil, err
		}
	}
	if query := tpq.withUser; query != nil {
		if err := tpq.loadUser(ctx, query, nodes, nil,
			func(n *TblPayment, e *TblUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tpq *TblPaymentQuery) loadInventory(ctx context.Context, query *TblInventoryQuery, nodes []*TblPayment, init func(*TblPayment), assign func(*TblPayment, *TblInventory)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TblPayment)
	for i := range nodes {
		fk := nodes[i].InventoryId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tblinventory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "InventoryId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tpq *TblPaymentQuery) loadUser(ctx context.Context, query *TblUserQuery, nodes []*TblPayment, init func(*TblPayment), assign func(*TblPayment, *TblUser)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*TblPayment)
	for i := range nodes {
		fk := nodes[i].UserId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tbluser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "UserId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tpq *TblPaymentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	if len(tpq.modifiers) > 0 {
		_spec.Modifiers = tpq.modifiers
	}
	_spec.Node.Columns = tpq.ctx.Fields
	if len(tpq.ctx.Fields) > 0 {
		_spec.Unique = tpq.ctx.Unique != nil && *tpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TblPaymentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tblpayment.Table, tblpayment.Columns, sqlgraph.NewFieldSpec(tblpayment.FieldID, field.TypeString))
	_spec.From = tpq.sql
	if unique := tpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tpq.path != nil {
		_spec.Unique = true
	}
	if fields := tpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tblpayment.FieldID)
		for i := range fields {
			if fields[i] != tblpayment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tpq.withInventory != nil {
			_spec.Node.AddColumnOnce(tblpayment.FieldInventoryId)
		}
		if tpq.withUser != nil {
			_spec.Node.AddColumnOnce(tblpayment.FieldUserId)
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TblPaymentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(tblpayment.Table)
	columns := tpq.ctx.Fields
	if len(columns) == 0 {
		columns = tblpayment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tpq.ctx.Unique != nil && *tpq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tpq.modifiers {
		m(selector)
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (tpq *TblPaymentQuery) ForUpdate(opts ...sql.LockOption) *TblPaymentQuery {
	if tpq.driver.Dialect() == dialect.Postgres {
		tpq.Unique(false)
	}
	tpq.modifiers = append(tpq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return tpq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (tpq *TblPaymentQuery) ForShare(opts ...sql.LockOption) *TblPaymentQuery {
	if tpq.driver.Dialect() == dialect.Postgres {
		tpq.Unique(false)
	}
	tpq.modifiers = append(tpq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return tpq
}

// TblPaymentGroupBy is the group-by builder for TblPayment entities.
type TblPaymentGroupBy struct {
	selector
	build *TblPaymentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TblPaymentGroupBy) Aggregate(fns ...AggregateFunc) *TblPaymentGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the selector query and scans the result into the given value.
func (tpgb *TblPaymentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tpgb.build.ctx, ent.OpQueryGroupBy)
	if err := tpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TblPaymentQuery, *TblPaymentGroupBy](ctx, tpgb.build, tpgb, tpgb.build.inters, v)
}

func (tpgb *TblPaymentGroupBy) sqlScan(ctx context.Context, root *TblPaymentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tpgb.flds)+len(tpgb.fns))
		for _, f := range *tpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TblPaymentSelect is the builder for selecting fields of TblPayment entities.
type TblPaymentSelect struct {
	*TblPaymentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tps *TblPaymentSelect) Aggregate(fns ...AggregateFunc) *TblPaymentSelect {
	tps.fns = append(tps.fns, fns...)
	return tps
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TblPaymentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tps.ctx, ent.OpQuerySelect)
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TblPaymentQuery, *TblPaymentSelect](ctx, tps.TblPaymentQuery, tps, tps.inters, v)
}

func (tps *TblPaymentSelect) sqlScan(ctx context.Context, root *TblPaymentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tps.fns))
	for _, fn := range tps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
