// Code generated by ent, DO NOT EDIT.

package entgen

import (
	"context"
	"database/sql/driver"
	"fmt"
	"inventory/ent/entgen/predicate"
	"inventory/ent/entgen/tblinventorytag"
	"inventory/ent/entgen/tbltag"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TblTagQuery is the builder for querying TblTag entities.
type TblTagQuery struct {
	config
	ctx              *QueryContext
	order            []tbltag.OrderOption
	inters           []Interceptor
	predicates       []predicate.TblTag
	withInventoryTag *TblInventoryTagQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TblTagQuery builder.
func (ttq *TblTagQuery) Where(ps ...predicate.TblTag) *TblTagQuery {
	ttq.predicates = append(ttq.predicates, ps...)
	return ttq
}

// Limit the number of records to be returned by this query.
func (ttq *TblTagQuery) Limit(limit int) *TblTagQuery {
	ttq.ctx.Limit = &limit
	return ttq
}

// Offset to start from.
func (ttq *TblTagQuery) Offset(offset int) *TblTagQuery {
	ttq.ctx.Offset = &offset
	return ttq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ttq *TblTagQuery) Unique(unique bool) *TblTagQuery {
	ttq.ctx.Unique = &unique
	return ttq
}

// Order specifies how the records should be ordered.
func (ttq *TblTagQuery) Order(o ...tbltag.OrderOption) *TblTagQuery {
	ttq.order = append(ttq.order, o...)
	return ttq
}

// QueryInventoryTag chains the current query on the "inventoryTag" edge.
func (ttq *TblTagQuery) QueryInventoryTag() *TblInventoryTagQuery {
	query := (&TblInventoryTagClient{config: ttq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ttq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ttq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tbltag.Table, tbltag.FieldID, selector),
			sqlgraph.To(tblinventorytag.Table, tblinventorytag.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tbltag.InventoryTagTable, tbltag.InventoryTagColumn),
		)
		fromU = sqlgraph.SetNeighbors(ttq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TblTag entity from the query.
// Returns a *NotFoundError when no TblTag was found.
func (ttq *TblTagQuery) First(ctx context.Context) (*TblTag, error) {
	nodes, err := ttq.Limit(1).All(setContextOp(ctx, ttq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tbltag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ttq *TblTagQuery) FirstX(ctx context.Context) *TblTag {
	node, err := ttq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TblTag ID from the query.
// Returns a *NotFoundError when no TblTag ID was found.
func (ttq *TblTagQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ttq.Limit(1).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tbltag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ttq *TblTagQuery) FirstIDX(ctx context.Context) string {
	id, err := ttq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TblTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TblTag entity is found.
// Returns a *NotFoundError when no TblTag entities are found.
func (ttq *TblTagQuery) Only(ctx context.Context) (*TblTag, error) {
	nodes, err := ttq.Limit(2).All(setContextOp(ctx, ttq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tbltag.Label}
	default:
		return nil, &NotSingularError{tbltag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ttq *TblTagQuery) OnlyX(ctx context.Context) *TblTag {
	node, err := ttq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TblTag ID in the query.
// Returns a *NotSingularError when more than one TblTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (ttq *TblTagQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = ttq.Limit(2).IDs(setContextOp(ctx, ttq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tbltag.Label}
	default:
		err = &NotSingularError{tbltag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ttq *TblTagQuery) OnlyIDX(ctx context.Context) string {
	id, err := ttq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TblTags.
func (ttq *TblTagQuery) All(ctx context.Context) ([]*TblTag, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryAll)
	if err := ttq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TblTag, *TblTagQuery]()
	return withInterceptors[[]*TblTag](ctx, ttq, qr, ttq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ttq *TblTagQuery) AllX(ctx context.Context) []*TblTag {
	nodes, err := ttq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TblTag IDs.
func (ttq *TblTagQuery) IDs(ctx context.Context) (ids []string, err error) {
	if ttq.ctx.Unique == nil && ttq.path != nil {
		ttq.Unique(true)
	}
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryIDs)
	if err = ttq.Select(tbltag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ttq *TblTagQuery) IDsX(ctx context.Context) []string {
	ids, err := ttq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ttq *TblTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryCount)
	if err := ttq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ttq, querierCount[*TblTagQuery](), ttq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ttq *TblTagQuery) CountX(ctx context.Context) int {
	count, err := ttq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ttq *TblTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ttq.ctx, ent.OpQueryExist)
	switch _, err := ttq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("entgen: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ttq *TblTagQuery) ExistX(ctx context.Context) bool {
	exist, err := ttq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TblTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ttq *TblTagQuery) Clone() *TblTagQuery {
	if ttq == nil {
		return nil
	}
	return &TblTagQuery{
		config:           ttq.config,
		ctx:              ttq.ctx.Clone(),
		order:            append([]tbltag.OrderOption{}, ttq.order...),
		inters:           append([]Interceptor{}, ttq.inters...),
		predicates:       append([]predicate.TblTag{}, ttq.predicates...),
		withInventoryTag: ttq.withInventoryTag.Clone(),
		// clone intermediate query.
		sql:  ttq.sql.Clone(),
		path: ttq.path,
	}
}

// WithInventoryTag tells the query-builder to eager-load the nodes that are connected to
// the "inventoryTag" edge. The optional arguments are used to configure the query builder of the edge.
func (ttq *TblTagQuery) WithInventoryTag(opts ...func(*TblInventoryTagQuery)) *TblTagQuery {
	query := (&TblInventoryTagClient{config: ttq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ttq.withInventoryTag = query
	return ttq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TblTag.Query().
//		GroupBy(tbltag.FieldName).
//		Aggregate(entgen.Count()).
//		Scan(ctx, &v)
func (ttq *TblTagQuery) GroupBy(field string, fields ...string) *TblTagGroupBy {
	ttq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TblTagGroupBy{build: ttq}
	grbuild.flds = &ttq.ctx.Fields
	grbuild.label = tbltag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.TblTag.Query().
//		Select(tbltag.FieldName).
//		Scan(ctx, &v)
func (ttq *TblTagQuery) Select(fields ...string) *TblTagSelect {
	ttq.ctx.Fields = append(ttq.ctx.Fields, fields...)
	sbuild := &TblTagSelect{TblTagQuery: ttq}
	sbuild.label = tbltag.Label
	sbuild.flds, sbuild.scan = &ttq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TblTagSelect configured with the given aggregations.
func (ttq *TblTagQuery) Aggregate(fns ...AggregateFunc) *TblTagSelect {
	return ttq.Select().Aggregate(fns...)
}

func (ttq *TblTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ttq.inters {
		if inter == nil {
			return fmt.Errorf("entgen: uninitialized interceptor (forgotten import entgen/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ttq); err != nil {
				return err
			}
		}
	}
	for _, f := range ttq.ctx.Fields {
		if !tbltag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entgen: invalid field %q for query", f)}
		}
	}
	if ttq.path != nil {
		prev, err := ttq.path(ctx)
		if err != nil {
			return err
		}
		ttq.sql = prev
	}
	return nil
}

func (ttq *TblTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TblTag, error) {
	var (
		nodes       = []*TblTag{}
		_spec       = ttq.querySpec()
		loadedTypes = [1]bool{
			ttq.withInventoryTag != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TblTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TblTag{config: ttq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(ttq.modifiers) > 0 {
		_spec.Modifiers = ttq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ttq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ttq.withInventoryTag; query != nil {
		if err := ttq.loadInventoryTag(ctx, query, nodes,
			func(n *TblTag) { n.Edges.InventoryTag = []*TblInventoryTag{} },
			func(n *TblTag, e *TblInventoryTag) { n.Edges.InventoryTag = append(n.Edges.InventoryTag, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ttq *TblTagQuery) loadInventoryTag(ctx context.Context, query *TblInventoryTagQuery, nodes []*TblTag, init func(*TblTag), assign func(*TblTag, *TblInventoryTag)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*TblTag)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tblinventorytag.FieldTagId)
	}
	query.Where(predicate.TblInventoryTag(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tbltag.InventoryTagColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TagId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "TagId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (ttq *TblTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ttq.querySpec()
	if len(ttq.modifiers) > 0 {
		_spec.Modifiers = ttq.modifiers
	}
	_spec.Node.Columns = ttq.ctx.Fields
	if len(ttq.ctx.Fields) > 0 {
		_spec.Unique = ttq.ctx.Unique != nil && *ttq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ttq.driver, _spec)
}

func (ttq *TblTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tbltag.Table, tbltag.Columns, sqlgraph.NewFieldSpec(tbltag.FieldID, field.TypeString))
	_spec.From = ttq.sql
	if unique := ttq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ttq.path != nil {
		_spec.Unique = true
	}
	if fields := ttq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tbltag.FieldID)
		for i := range fields {
			if fields[i] != tbltag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ttq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ttq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ttq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ttq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ttq *TblTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ttq.driver.Dialect())
	t1 := builder.Table(tbltag.Table)
	columns := ttq.ctx.Fields
	if len(columns) == 0 {
		columns = tbltag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ttq.sql != nil {
		selector = ttq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ttq.ctx.Unique != nil && *ttq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ttq.modifiers {
		m(selector)
	}
	for _, p := range ttq.predicates {
		p(selector)
	}
	for _, p := range ttq.order {
		p(selector)
	}
	if offset := ttq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ttq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (ttq *TblTagQuery) ForUpdate(opts ...sql.LockOption) *TblTagQuery {
	if ttq.driver.Dialect() == dialect.Postgres {
		ttq.Unique(false)
	}
	ttq.modifiers = append(ttq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return ttq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (ttq *TblTagQuery) ForShare(opts ...sql.LockOption) *TblTagQuery {
	if ttq.driver.Dialect() == dialect.Postgres {
		ttq.Unique(false)
	}
	ttq.modifiers = append(ttq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return ttq
}

// TblTagGroupBy is the group-by builder for TblTag entities.
type TblTagGroupBy struct {
	selector
	build *TblTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ttgb *TblTagGroupBy) Aggregate(fns ...AggregateFunc) *TblTagGroupBy {
	ttgb.fns = append(ttgb.fns, fns...)
	return ttgb
}

// Scan applies the selector query and scans the result into the given value.
func (ttgb *TblTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ttgb.build.ctx, ent.OpQueryGroupBy)
	if err := ttgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TblTagQuery, *TblTagGroupBy](ctx, ttgb.build, ttgb, ttgb.build.inters, v)
}

func (ttgb *TblTagGroupBy) sqlScan(ctx context.Context, root *TblTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ttgb.fns))
	for _, fn := range ttgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ttgb.flds)+len(ttgb.fns))
		for _, f := range *ttgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ttgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ttgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TblTagSelect is the builder for selecting fields of TblTag entities.
type TblTagSelect struct {
	*TblTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tts *TblTagSelect) Aggregate(fns ...AggregateFunc) *TblTagSelect {
	tts.fns = append(tts.fns, fns...)
	return tts
}

// Scan applies the selector query and scans the result into the given value.
func (tts *TblTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tts.ctx, ent.OpQuerySelect)
	if err := tts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TblTagQuery, *TblTagSelect](ctx, tts.TblTagQuery, tts, tts.inters, v)
}

func (tts *TblTagSelect) sqlScan(ctx context.Context, root *TblTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tts.fns))
	for _, fn := range tts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
