// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// TblAuthClient is the predicate function for tblauthclient builders.
type TblAuthClient func(*sql.Selector)

// TblAuthToken is the predicate function for tblauthtoken builders.
type TblAuthToken func(*sql.Selector)

// TblCart is the predicate function for tblcart builders.
type TblCart func(*sql.Selector)

// TblInventory is the predicate function for tblinventory builders.
type TblInventory func(*sql.Selector)

// TblInventoryTag is the predicate function for tblinventorytag builders.
type TblInventoryTag func(*sql.Selector)

// TblPayment is the predicate function for tblpayment builders.
type TblPayment func(*sql.Selector)

// TblTag is the predicate function for tbltag builders.
type TblTag func(*sql.Selector)

// TblUser is the predicate function for tbluser builders.
type TblUser func(*sql.Selector)
