// Code generated by ent, DO NOT EDIT.

package tblpayment

import (
	"inventory/ent/entgen/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContainsFold(FieldID, id))
}

// InventoryId applies equality check predicate on the "InventoryId" field. It's identical to InventoryIdEQ.
func InventoryId(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldInventoryId, v))
}

// UserId applies equality check predicate on the "UserId" field. It's identical to UserIdEQ.
func UserId(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldUserId, v))
}

// Status applies equality check predicate on the "Status" field. It's identical to StatusEQ.
func Status(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldStatus, v))
}

// RazorpayOrderId applies equality check predicate on the "RazorpayOrderId" field. It's identical to RazorpayOrderIdEQ.
func RazorpayOrderId(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldRazorpayOrderId, v))
}

// Amount applies equality check predicate on the "Amount" field. It's identical to AmountEQ.
func Amount(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldAmount, v))
}

// CreatedAt applies equality check predicate on the "Created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "Updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "Deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldDeletedAt, v))
}

// InventoryIdEQ applies the EQ predicate on the "InventoryId" field.
func InventoryIdEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldInventoryId, v))
}

// InventoryIdNEQ applies the NEQ predicate on the "InventoryId" field.
func InventoryIdNEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldInventoryId, v))
}

// InventoryIdIn applies the In predicate on the "InventoryId" field.
func InventoryIdIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldInventoryId, vs...))
}

// InventoryIdNotIn applies the NotIn predicate on the "InventoryId" field.
func InventoryIdNotIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldInventoryId, vs...))
}

// InventoryIdGT applies the GT predicate on the "InventoryId" field.
func InventoryIdGT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldInventoryId, v))
}

// InventoryIdGTE applies the GTE predicate on the "InventoryId" field.
func InventoryIdGTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldInventoryId, v))
}

// InventoryIdLT applies the LT predicate on the "InventoryId" field.
func InventoryIdLT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldInventoryId, v))
}

// InventoryIdLTE applies the LTE predicate on the "InventoryId" field.
func InventoryIdLTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldInventoryId, v))
}

// InventoryIdContains applies the Contains predicate on the "InventoryId" field.
func InventoryIdContains(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContains(FieldInventoryId, v))
}

// InventoryIdHasPrefix applies the HasPrefix predicate on the "InventoryId" field.
func InventoryIdHasPrefix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasPrefix(FieldInventoryId, v))
}

// InventoryIdHasSuffix applies the HasSuffix predicate on the "InventoryId" field.
func InventoryIdHasSuffix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasSuffix(FieldInventoryId, v))
}

// InventoryIdIsNil applies the IsNil predicate on the "InventoryId" field.
func InventoryIdIsNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIsNull(FieldInventoryId))
}

// InventoryIdNotNil applies the NotNil predicate on the "InventoryId" field.
func InventoryIdNotNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotNull(FieldInventoryId))
}

// InventoryIdEqualFold applies the EqualFold predicate on the "InventoryId" field.
func InventoryIdEqualFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEqualFold(FieldInventoryId, v))
}

// InventoryIdContainsFold applies the ContainsFold predicate on the "InventoryId" field.
func InventoryIdContainsFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContainsFold(FieldInventoryId, v))
}

// UserIdEQ applies the EQ predicate on the "UserId" field.
func UserIdEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "UserId" field.
func UserIdNEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "UserId" field.
func UserIdIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "UserId" field.
func UserIdNotIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldUserId, vs...))
}

// UserIdGT applies the GT predicate on the "UserId" field.
func UserIdGT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldUserId, v))
}

// UserIdGTE applies the GTE predicate on the "UserId" field.
func UserIdGTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldUserId, v))
}

// UserIdLT applies the LT predicate on the "UserId" field.
func UserIdLT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldUserId, v))
}

// UserIdLTE applies the LTE predicate on the "UserId" field.
func UserIdLTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldUserId, v))
}

// UserIdContains applies the Contains predicate on the "UserId" field.
func UserIdContains(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContains(FieldUserId, v))
}

// UserIdHasPrefix applies the HasPrefix predicate on the "UserId" field.
func UserIdHasPrefix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasPrefix(FieldUserId, v))
}

// UserIdHasSuffix applies the HasSuffix predicate on the "UserId" field.
func UserIdHasSuffix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasSuffix(FieldUserId, v))
}

// UserIdIsNil applies the IsNil predicate on the "UserId" field.
func UserIdIsNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIsNull(FieldUserId))
}

// UserIdNotNil applies the NotNil predicate on the "UserId" field.
func UserIdNotNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotNull(FieldUserId))
}

// UserIdEqualFold applies the EqualFold predicate on the "UserId" field.
func UserIdEqualFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEqualFold(FieldUserId, v))
}

// UserIdContainsFold applies the ContainsFold predicate on the "UserId" field.
func UserIdContainsFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContainsFold(FieldUserId, v))
}

// StatusEQ applies the EQ predicate on the "Status" field.
func StatusEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "Status" field.
func StatusNEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "Status" field.
func StatusIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "Status" field.
func StatusNotIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "Status" field.
func StatusGT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "Status" field.
func StatusGTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "Status" field.
func StatusLT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "Status" field.
func StatusLTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "Status" field.
func StatusContains(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "Status" field.
func StatusHasPrefix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "Status" field.
func StatusHasSuffix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "Status" field.
func StatusEqualFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "Status" field.
func StatusContainsFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContainsFold(FieldStatus, v))
}

// RazorpayOrderIdEQ applies the EQ predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdNEQ applies the NEQ predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdNEQ(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdIn applies the In predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldRazorpayOrderId, vs...))
}

// RazorpayOrderIdNotIn applies the NotIn predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdNotIn(vs ...string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldRazorpayOrderId, vs...))
}

// RazorpayOrderIdGT applies the GT predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdGT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdGTE applies the GTE predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdGTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdLT applies the LT predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdLT(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdLTE applies the LTE predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdLTE(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdContains applies the Contains predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdContains(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContains(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdHasPrefix applies the HasPrefix predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdHasPrefix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasPrefix(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdHasSuffix applies the HasSuffix predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdHasSuffix(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldHasSuffix(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdEqualFold applies the EqualFold predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdEqualFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEqualFold(FieldRazorpayOrderId, v))
}

// RazorpayOrderIdContainsFold applies the ContainsFold predicate on the "RazorpayOrderId" field.
func RazorpayOrderIdContainsFold(v string) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldContainsFold(FieldRazorpayOrderId, v))
}

// AmountEQ applies the EQ predicate on the "Amount" field.
func AmountEQ(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "Amount" field.
func AmountNEQ(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "Amount" field.
func AmountIn(vs ...float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "Amount" field.
func AmountNotIn(vs ...float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "Amount" field.
func AmountGT(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "Amount" field.
func AmountGTE(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "Amount" field.
func AmountLT(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "Amount" field.
func AmountLTE(v float32) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "Created_at" field.
func CreatedAtEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "Created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "Created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "Created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "Created_at" field.
func CreatedAtGT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "Created_at" field.
func CreatedAtGTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "Created_at" field.
func CreatedAtLT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "Created_at" field.
func CreatedAtLTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "Updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "Updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "Updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "Updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "Updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "Updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "Updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "Updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "Deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "Deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "Deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "Deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "Deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "Deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "Deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "Deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TblPayment {
	return predicate.TblPayment(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "Deleted_at" field.
func DeletedAtIsNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "Deleted_at" field.
func DeletedAtNotNil() predicate.TblPayment {
	return predicate.TblPayment(sql.FieldNotNull(FieldDeletedAt))
}

// HasInventory applies the HasEdge predicate on the "Inventory" edge.
func HasInventory() predicate.TblPayment {
	return predicate.TblPayment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, InventoryTable, InventoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryWith applies the HasEdge predicate on the "Inventory" edge with a given conditions (other predicates).
func HasInventoryWith(preds ...predicate.TblInventory) predicate.TblPayment {
	return predicate.TblPayment(func(s *sql.Selector) {
		step := newInventoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "User" edge.
func HasUser() predicate.TblPayment {
	return predicate.TblPayment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "User" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.TblUser) predicate.TblPayment {
	return predicate.TblPayment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TblPayment) predicate.TblPayment {
	return predicate.TblPayment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TblPayment) predicate.TblPayment {
	return predicate.TblPayment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TblPayment) predicate.TblPayment {
	return predicate.TblPayment(sql.NotPredicates(p))
}
