name: Build & Push Docker Image

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Create a lowercase repo slug and export it to $REPO_LC
      - name: Lowercase repo name
        run: |
          echo "REPO_LC=$(echo '${GITHUB_REPOSITORY}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 3) Log in to GHCR
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Build & push, referencing the env var via ${{ env.REPO_LC }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mitti-more-go-backend:latest
